"""Tests for the Atropos-style RL environment wrapper.

No mock agent involved: a "perfect reply" for a clearance turn is built
directly from the turn's own ground-truth `expected_values` (already known
from rendering the scenario), not generated by a simulated pilot. This is a
test fixture for exercising env.step()'s turn-advancement and scoring logic,
not a stand-in for a real agent's behavior.
"""
from orchestrator.scenario_loader import load_scenario_yaml, render_scenario, SCENARIOS_DIR
from export.atropos_env import RogerThatEnv

_KEYWORD = {"fl": "fl", "qnh": "qnh", "hdg": "hdg", "spd": "speed", "freq": "freq", "rwy": "rwy", "squawk": "squawk"}


def _perfect_reply(turn, own_callsign_display):
    if turn.type == "clearance":
        parts = [f"{_KEYWORD[item]} {value}" for item, value in turn.expected_values.items() if item != "callsign"]
        parts.append(own_callsign_display)
        return " ".join(parts)
    if turn.type in ("trap", "clutter"):
        return ""  # correct behavior: silence
    raise ValueError(f"no scripted reply builder for turn type: {turn.type}")


def test_env_matches_ground_truth_perfect_score():
    scenario = load_scenario_yaml(SCENARIOS_DIR / "callsign-trap-01.yaml")
    rs = render_scenario(scenario, seed=42)
    env = RogerThatEnv(scenario)
    obs = env.reset(seed=42)

    done = False
    reward = None
    turn_index = 0
    while not done:
        turn = rs.turns[turn_index]
        action = _perfect_reply(turn, rs.callsign["display"])
        result = env.step(action)
        done = result.done
        reward = result.reward
        obs = result.observation
        if not done and obs["turn_type"] != "clearance_retry":
            turn_index += 1

    assert reward == 1.0


def test_env_retry_step_is_offered_on_bad_readback():
    scenario = load_scenario_yaml(SCENARIOS_DIR / "simple-descent-01.yaml")
    env = RogerThatEnv(scenario)
    obs = env.reset(seed=1)
    assert obs["turn_type"] == "clearance"
    result = env.step("roger")  # no items read back at all
    assert result.observation["turn_type"] == "clearance_retry"
    assert result.done is False
